### ISSUE TITLE
Adopt extensions to agcontext from Asher

### ISSUE THREAD

**Issue by jnothman** [Sydney-Informatics-Hub/Weed-ID-Interchange#72]
@asherbender proposed being able to record the following attributes as context of data collection:
```yaml
#-------------------------------------------------------------------------------
#                                 institution
#-------------------------------------------------------------------------------

# Description: Name of organisation/institution that collected the data.
# Requirement: Mandatory.
# Type:        string
institution_name:

# Description: Name of project that data was collected under.
# Requirement: Optional (uncomment and edit).
# Type:        string
# Default:
#institution_project:

# Description: Name of organisation/institution that funded the data collection.
# Requirement: Optional (uncomment and edit).
# Type:        string
# Default:
#institution_funding:

# Description: Name of individuals responsible for collecting the data.
# Requirement: Optional (uncomment and edit).
# Type:        string
# Default:     anonymous
#institution_authors:

# Description: Description of organisation/institution/individuals that
#              collected the data.
# Requirement: Optional (uncomment and edit).
# Type:        string
# Default:
#institution_notes:

#-------------------------------------------------------------------------------
#                                    system
#-------------------------------------------------------------------------------

# Description: Name of data collection system.
# Requirement: Optional (uncomment and edit).
# Type:        string
# Default:
#system_name:

# Description: Description of data collection system.
# Requirement: Optional (uncomment and edit).
# Type:        string
# Default:
#system_description:

# Description: Operational space where data collection system operates.
# Requirement: Mandatory.
# Type:        enum
# Options:     ['marine', 'terrestrial', 'aerial', 'space']
system_theatre:

# Description: Mobility of data collection system. Static data collection
#              systems remain stationary and collect data in only one location.
#              Mobile data collection systems are capable of locomotion and can
#              collect data from multiple locations.
# Requirement: Mandatory.
# Type:        enum
# Options:     ['static', 'mobile']
system_mobility:

# Description: Method of controlling the data collection platform. Handheld
#              control are systems that are physically carried by a human
#              operator (e.g. digital camera). Direct control are systems that
#              are controlled by a human operator on or within the platform
#              (e.g. driving a tractor). Remote control are systems that are
#              controlled by a human operator outside the platform (e.g.
#              manually piloting a drone). Autonomous control are systems that
#              operate without human assistance (e.g. autonomous vehicle).
# Requirement: Mandatory.
# Type:        enum
# Options:     ['handheld', 'direct', 'remote', 'autonomous']
system_control:

#-------------------------------------------------------------------------------
#                                   location
#-------------------------------------------------------------------------------

# Description: Country where data was collected.
# Requirement: Optional (uncomment and edit).
# Type:        string
# Default:
#location_country:

# Description: State/province where data was collected.
# Requirement: Optional (uncomment and edit).
# Type:        string
# Default:
#location_state:

# Description: City where data was collected.
# Requirement: Optional (uncomment and edit).
# Type:        string
# Default:
#location_city:

# Description: Latitude in decimal degrees where data was collected.
# Requirement: Optional (uncomment and edit).
# Type:        float
# Default:     nan
# Unit:        Decimal degrees (DD)
#location_latitude:

# Description: Longitude in decimal degrees where data was collected.
# Requirement: Optional (uncomment and edit).
# Type:        float
# Default:     nan
# Unit:        Decimal degrees (DD)
#location_longitude:

# Description: Spatial reference system of latitude/longitude expressed as an
#              EPSG code (e.g. WGS 84 is 4326).
# Requirement: Optional (uncomment and edit).
# Type:        int
# Default:     0
#location_epsg:

#-------------------------------------------------------------------------------
#                                   weather
#-------------------------------------------------------------------------------

# Description: Average temperature during data collection in degrees Celsius.
# Requirement: Optional (uncomment and edit).
# Type:        float
# Default:     nan
# Unit:        Degrees Celsius (C)
#weather_temperature:

# Description: Average relative humidity during data collection as a percentage.
# Requirement: Optional (uncomment and edit).
# Type:        float
# Default:     nan
# Unit:        Percentage (%)
#weather_humidity:

# Description: Average barometric pressure during data collection in
#              hectopascals (hPa).
# Requirement: Optional (uncomment and edit).
# Type:        float
# Default:     nan
# Unit:        Hectopascal (hPa)
#weather_pressure:

# Description: Subjective cloud cover during data collection.
# Requirement: Optional (uncomment and edit).
# Type:        enum
# Options:     ['unknown', 'none', 'light', 'intermediate', 'heavy']
# Default:     unknown
#weather_cloud_cover:

# Description: Subjective atmospheric clarity during data collection. Note that
#              this condition is distinct from cloud cover. Atmospheric clarity
#              covers conditions such as pollution or haze due to bushfires.
# Requirement: Optional (uncomment and edit).
# Type:        enum
# Options:     ['unknown', 'clear', 'intermediate haze', 'heavy haze']
# Default:     unknown
#weather_atmospheric_clarity:

# Description: Average rainfall during data collection in millimetres (mm).
# Requirement: Optional (uncomment and edit).
# Type:        float
# Default:     nan
# Unit:        Millimetres (mm)
#weather_rainfall:

# Description: Subjective rain conditions during data collection.
# Requirement: Optional (uncomment and edit).
# Type:        enum
# Options:     ['unknown', 'none', 'light', 'intermediate', 'heavy']
# Default:     unknown
#weather_rain_qualitative:

# Description: Average wind speed during data collection in metres per second
#              (m/s).
# Requirement: Optional (uncomment and edit).
# Type:        float
# Default:     nan
# Unit:        Metres per second (m/s)
#weather_wind_speed:

# Description: Average wind direction during data collection in degrees from
#              North.
# Requirement: Optional (uncomment and edit).
# Type:        float
# Default:     nan
# Unit:        Degrees from north
#weather_wind_direction:

# Description: Subjective wind conditions during data collection.
# Requirement: Optional (uncomment and edit).
# Type:        enum
# Options:     ['unknown', 'none', 'light', 'intermediate', 'heavy']
# Default:     unknown
#weather_wind_qualitative:

# Description: True if dew was present during data collection.
# Requirement: Optional (uncomment and edit).
# Type:        bool
# Default:     False
#weather_dew:

# Description: True if frost was present during data collection.
# Requirement: Optional (uncomment and edit).
# Type:        bool
# Default:     False
#weather_frost:

# Description: True if mist or fog was present during data collection.
# Requirement: Optional (uncomment and edit).
# Type:        bool
# Default:     False
#weather_mist:

# Description: True if snow was present during data collection.
# Requirement: Optional (uncomment and edit).
# Type:        bool
# Default:     False
#weather_snow:

# Description: Description of weather conditions during data collection.
# Requirement: Optional (uncomment and edit).
# Type:        string
# Default:
#weather_notes:
```
